name: GG-Status
version: '1.0.0'
main: net.griefergamez.ggzstatus.Status
api-version: '1.21'
authors: [ FlexKleks ]
description: Status command
website: https://griefergame.net
depend: [LuckPerms]
commands:
  status:
    description: Setze deinen Status für den Join-Chat
    usage: /status <set|sound|toggle|delete|block|unblock>
    aliases: [ st ]